language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
cache: pip
install:
  - pip install coverage
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
