name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on your first issue to the PyAlgo project!'
        pr-message: 'Thank you for contributing to PyAlgo! Do check CONTRIBUTING.md'
